name: stadia_scanner
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:

  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6

  flutter_svg: ^2.0.10+1
  mobile_scanner: ^4.0.1
  mongo_dart: ^0.10.0
  shared_preferences: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

#flutter_native_splash:
#  color: "#ffffff"
#  image: assets/images/app_icon.ico

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
  uses-material-design: true
  assets:
    - assets/images/
